# Generated by Django 6.1 on 2026-08-22 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('notice_title', models.CharField(max_length=255)),
                ('confidence', models.CharField(default='N/A', max_length=50)),
                ('status', models.CharField(default='Success', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='General', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('file_type', models.CharField(default='PDF Document', max_length=50)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source_institution', models.CharField(default='MIT World Peace University', max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by_user', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='General', max_length=100)),
                ('action_required', models.TextField()),
                ('due_date', models.DateField()),
                ('due_time', models.CharField(default='17:00', max_length=20)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('eligibility', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Completed', 'Completed'), ('Missed', 'Missed')], default='Upcoming', max_length=20)),
                ('reminder_set', models.BooleanField(default=False)),
                ('file_type', models.CharField(default='PDF Document', max_length=50)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source_institution', models.CharField(default='MIT World Peace University', max_length=255)),
                ('extracted_confidence', models.FloatField(default=95.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadlines', to=settings.AUTH_USER_MODEL)),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='api.notice')),
            ],
            options={
                'ordering': ['due_date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='AIExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_action', models.TextField()),
                ('extracted_deadline', models.DateField(blank=True, null=True)),
                ('extracted_due_time', models.CharField(default='17:00', max_length=20)),
                ('extracted_priority', models.CharField(default='Medium', max_length=20)),
                ('extracted_eligibility', models.TextField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=95.0)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_extraction', to='api.notice')),
            ],
        ),
        migrations.CreateModel(
            name='OCRText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField()),
                ('extraction_method', models.CharField(default='PyTesseract OCR', max_length=50)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_data', to='api.notice')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('channel', models.CharField(default='Email & WhatsApp', max_length=100)),
                ('trigger_date', models.CharField(max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Dispatched', 'Dispatched'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('offset', models.CharField(default='2 days before', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='api.deadline')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_prn', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('department', models.CharField(default='School of Computer Science & Applications', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(default='student', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
