# Generated by Django 5.2.17 on 2026-10-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='notice',
            name='document_bytes',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
