# Generated by Django 5.2.17 on 2026-10-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notice_content_type_notice_document_bytes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='due_time',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
